<?php

/**
 * @var  \Magento360\Base\Block\WebsiteSwitcher $block;
 */
?>
<?php if (count($block->getWebsites())>1) : ?>
    <div class="switcher website switcher-website" data-ui-id="language-switcher" id="switcher-website">
        <strong class="switcher-label"><span><?= $block->escapeHtml(__('Select Store:')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger"
                 id="switcher-website-trigger"
                 data-mage-init='{"dropdown":{}}'
                 data-toggle="dropdown"
                 data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentWebsiteCode()) ?>">
                    <span><?= $block->escapeHtml(__($block->getCurrentWebsiteName())) ?></span>
                </strong>
            </div>
            <ul class="dropdown switcher-dropdown"
                data-target="dropdown">
                <?php foreach ($block->getWebsites() as $_web) : ?>
                    <?php if ($_web->getId() != $block->getCurrentWebsiteId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_web->getCode()) ?> switcher-option">
                            <a href="<?php echo $_web->getDefaultStore()->getBaseUrl() ?>">
                                <?= $block->escapeHtml(__($_web->getName())) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                    <?php if ($_web->getId() == $block->getCurrentWebsiteId()) : ?>
                        <li class="view-<?= $block->escapeHtml($_web->getCode()) ?> switcher-option">
                            <a><?= $block->escapeHtml(__($_web->getName())) ?></a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
